{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "a84373ae_41579e24",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 24824
      },
      "writtenOn": "2022-09-20T15:34:49Z",
      "side": 1,
      "message": "A vault unit is in the error state which is unrelated to the change.\n\n2022-09-20 14:24:36.543558 | focal-medium | 2022-09-20 14:24:36 [ERROR] unit-vault-0.log: 2022-09-20 14:24:36 DEBUG juju.worker.uniter.runner runner.go:716 starting jujuc server  {unix @/var/lib/juju/agents/unit-vault-0/agent.socket \u003cnil\u003e}\n2022-09-20 14:24:36.543630 | focal-medium | 2022-09-20 14:24:36 [ERROR] unit-vault-0.log:\n2022-09-20 14:24:37.655518 | focal-medium | Traceback (most recent call last):\n2022-09-20 14:24:37.655606 | focal-medium |   File \"/home/ubuntu/src/review.opendev.org/x/charm-ovn-dedicated-chassis/src/.tox/func-target/bin/functest-run-suite\", line 8, in \u003cmodule\u003e\n2022-09-20 14:24:37.655650 | focal-medium |     sys.exit(main())\n2022-09-20 14:24:37.655699 | focal-medium |   File \"/home/ubuntu/src/review.opendev.org/x/charm-ovn-dedicated-chassis/src/.tox/func-target/lib/python3.8/site-packages/zaza/charm_lifecycle/func_test_runner.py\", line 395, in main\n2022-09-20 14:24:37.655721 | focal-medium |     func_test_runner(\n2022-09-20 14:24:37.655736 | focal-medium |   File \"/home/ubuntu/src/review.opendev.org/x/charm-ovn-dedicated-chassis/src/.tox/func-target/lib/python3.8/site-packages/zaza/charm_lifecycle/func_test_runner.py\", line 303, in func_test_runner\n2022-09-20 14:24:37.655750 | focal-medium |     run_env_deployment(env_deployment, keep_model\u003dpreserve_model,\n2022-09-20 14:24:37.655764 | focal-medium |   File \"/home/ubuntu/src/review.opendev.org/x/charm-ovn-dedicated-chassis/src/.tox/func-target/lib/python3.8/site-packages/zaza/charm_lifecycle/func_test_runner.py\", line 164, in run_env_deployment\n2022-09-20 14:24:37.655777 | focal-medium |     configure.configure(\n2022-09-20 14:24:37.655790 | focal-medium |   File \"/home/ubuntu/src/review.opendev.org/x/charm-ovn-dedicated-chassis/src/.tox/func-target/lib/python3.8/site-packages/zaza/charm_lifecycle/configure.py\", line 58, in configure\n2022-09-20 14:24:37.655803 | focal-medium |     run_configure_list(functions)\n2022-09-20 14:24:37.655835 | focal-medium |   File \"/usr/lib/python3.8/contextlib.py\", line 75, in inner\n2022-09-20 14:24:37.655866 | focal-medium |     return func(*args, **kwds)\n2022-09-20 14:24:37.655883 | focal-medium |   File \"/home/ubuntu/src/review.opendev.org/x/charm-ovn-dedicated-chassis/src/.tox/func-target/lib/python3.8/site-packages/zaza/charm_lifecycle/configure.py\", line 44, in run_configure_list\n2022-09-20 14:24:37.655897 | focal-medium |     utils.get_class(func)()\n2022-09-20 14:24:37.655910 | focal-medium |   File \"/home/ubuntu/src/review.opendev.org/x/charm-ovn-dedicated-chassis/src/.tox/func-target/lib/python3.8/site-packages/zaza/openstack/charm_tests/vault/setup.py\", line 182, in auto_initialize\n2022-09-20 14:24:37.655924 | focal-medium |     zaza.model.wait_for_application_states(\n2022-09-20 14:24:37.655937 | focal-medium |   File \"/home/ubuntu/src/review.opendev.org/x/charm-ovn-dedicated-chassis/src/.tox/func-target/lib/python3.8/site-packages/zaza/__init__.py\", line 224, in _wrapper\n2022-09-20 14:24:37.655954 | focal-medium |     return future.result(timeout)\n2022-09-20 14:24:37.655991 | focal-medium |   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 444, in result\n2022-09-20 14:24:37.656017 | focal-medium |     return self.__get_result()\n2022-09-20 14:24:37.656038 | focal-medium |   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n2022-09-20 14:24:37.656072 | focal-medium |     raise self._exception\n2022-09-20 14:24:37.656094 | focal-medium |   File \"/home/ubuntu/src/review.opendev.org/x/charm-ovn-dedicated-chassis/src/.tox/func-target/lib/python3.8/site-packages/zaza/__init__.py\", line 209, in _runner\n2022-09-20 14:24:37.656108 | focal-medium |     return await f(*args, **kwargs)\n2022-09-20 14:24:37.656121 | focal-medium |   File \"/home/ubuntu/src/review.opendev.org/x/charm-ovn-dedicated-chassis/src/.tox/func-target/lib/python3.8/site-packages/zaza/model.py\", line 1544, in async_wait_for_application_states\n2022-09-20 14:24:37.656135 | focal-medium |     check_model_for_hard_errors(model)\n2022-09-20 14:24:37.656148 | focal-medium |   File \"/home/ubuntu/src/review.opendev.org/x/charm-ovn-dedicated-chassis/src/.tox/func-target/lib/python3.8/site-packages/zaza/model.py\", line 1340, in check_model_for_hard_errors\n2022-09-20 14:24:37.656161 | focal-medium |     raise UnitError(errored_units)\n2022-09-20 14:24:37.656174 | focal-medium | zaza.model.UnitError: Units vault/0 in error state\n",
      "revId": "f7a4a460adea9a4720d697fcc382f2001ff814b5",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    }
  ]
}